# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy.

To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook.

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [ ]:
# Imports
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [ ]:
# Import applicants_data.csv to Google Colab

In [ ]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv('/content/resources/applicants_data.csv')

# Review the DataFrame
applicant_data_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Review the data types associated with the columns
applicant_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   EIN                     34299 non-null  int64
 1   NAME                    34299 non-null  object
 2   APPLICATION_TYPE        34299 non-null  object
 3   AFFILIATION             34299 non-null  object
 4   CLASSIFICATION          34299 non-null  object
 5   USE_CASE                34299 non-null  object
 6   ORGANIZATION            34299 non-null  object
 7   STATUS                  34299 non-null  int64
 8   INCOME_AMT              34299 non-null  object
 9   SPECIAL_CONSIDERATIONS  34299 non-null  object
 10  ASK_AMT                 34299 non-null  int64
 11  IS_SUCCESSFUL           34299 non-null  int64
dtypes: int64(4), object(8)
memory usage: 3.1+ MB

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [ ]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(columns=["EIN", "NAME"])
# Review the DataFrame
applicant_data_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [ ]:
# Define the target set by selecting the isFraud column
y = applicant_data_df["IS_SUCCESSFUL"]

# Display a sample of y
y[:5]

0    1
1    1
2    0
3    1
4    1
Name: IS_SUCCESSFUL, dtype: int64

In [ ]:
# Define features set X by selecting all columns but the IS_SUCCESSFUL
X = applicant_data_df.drop(columns=["IS_SUCCESSFUL"])

# Display the features DataFrame
X.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [ ]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [ ]:
list(applicant_data_df.dtypes[applicant_data_df.dtypes == "object"].index)

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [ ]:
# Create a list of categorical variables
categorical_variables = ["APPLICATION_TYPE", "AFFILIATION", "CLASSIFICATION", "USE_CASE", "ORGANIZATION","SPECIAL_CONSIDERATIONS"]

# Use the fit_transform method from the OneHotEncoder to encode the data
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [ ]:

# Create a DataFrame with the encoded variables
encoded_data_df = encoded_data = pd.DataFrame(
    encoded_data,
    columns = enc.get_feature_names_out(categorical_variables)
)

# Review the DataFrame
encoded_data_df.head()

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,USE_CASE_Heathcare,USE_CASE_Other,USE_CASE_Preservation,USE_CASE_ProductDev,ORGANIZATION_Association,ORGANIZATION_Co-operative,ORGANIZATION_Corporation,ORGANIZATION_Trust,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [ ]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded_df = pd.concat([applicant_data_df, encoded_data_df], axis =1)

# Review the DataFrame
encoded_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL,...,USE_CASE_Heathcare,USE_CASE_Other,USE_CASE_Preservation,USE_CASE_ProductDev,ORGANIZATION_Association,ORGANIZATION_Co-operative,ORGANIZATION_Corporation,ORGANIZATION_Trust,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [ ]:
# Define the target set by selecting the isFraud column
y = applicant_data_df["IS_SUCCESSFUL"]

# Display a sample of y
y[:5]

0    1
1    1
2    0
3    1
4    1
Name: IS_SUCCESSFUL, dtype: int64

In [ ]:
# Define features set X by selecting all columns but the isFraud
X = applicant_data_df.drop(columns=["IS_SUCCESSFUL"])

# Display the features DataFrame
X.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590

In [ ]:
# Encode the categorical variables using get_dummies
X = pd.get_dummies(X)

X.head()

,STATUS,ASK_AMT,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

### Step 6: Split the features and target sets into training and testing datasets.

In [ ]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [ ]:
# Create a StandardScaler instance
X_scaler = StandardScaler()

In [ ]:
# Fit the scaler to the features training dataset
X_scaler.fit(X_train)

StandardScaler()

In [ ]:
# Scale both the training and testing data from the features dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [ ]:
# Define the the number of inputs (features) to the model
number_input_features = 116

# Review the number of features
number_input_features

116

In [ ]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [ ]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 = 60

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

60

In [ ]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  32

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

32

In [ ]:
# Create the Sequential model instance
nn = Sequential()

In [ ]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

In [ ]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))

In [ ]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(1, activation="sigmoid"))

In [ ]:
# Display the Sequential model summary
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 60)                7020

 dense_1 (Dense)             (None, 32)                1952

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 9,005
Trainable params: 9,005
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [27]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [28]:
# Fit the model using 50 epochs and the training data
model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 4s 3ms/step - loss: 0.5742 - accuracy: 0.7178
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5531 - accuracy: 0.7302
Epoch 3/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5499 - accuracy: 0.7320
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5472 - accuracy: 0.7336
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5456 - accuracy: 0.7330
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5445 - accuracy: 0.7338
Epoch 7/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5433 - accuracy: 0.7342
Epoch 8/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5432 - accuracy: 0.7342
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7349
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7362
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7366
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7358
Epoch 13/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5401 - accuracy: 0.7364
Epoch 14/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5394 - accuracy: 0.7360
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7365
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7371
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7365
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7371
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7369
Epoch 20/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5371 - accuracy: 0.7365
Epoch 21/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5373 - accuracy: 0.7383
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7388
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7362
Epoch 24/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5361 - accuracy: 0.7385
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7389
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7395
Epoch 27/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5353 - accuracy: 0.7386
Epoch 28/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5351 - accuracy: 0.7384
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7385
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7403
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7384
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7389
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7396
Epoch 34/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5338 - accuracy: 0.7392
Epoch 35/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5333 - accuracy: 0.7408
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7403
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5333 - accuracy: 0.7400
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5333 - accuracy: 0.7407
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7406
Epoch 40/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5326 - accuracy: 0.7409
Epoch 41/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5332 - accuracy: 0.7404
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5329 - accuracy: 0.7404
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5322 - accuracy: 0.7404
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5323 - accuracy: 0.7415
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5321 - accuracy: 0.7400
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5320 - accuracy: 0.7409
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5317 - accuracy: 0.7414
Epoch 48/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5317 - accuracy: 0.7407
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5314 - accuracy: 0.7409
Epoch 50/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5314 - accuracy: 0.7409

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [29]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5578 - accuracy: 0.7282 - 521ms/epoch - 2ms/step
Loss: 0.5577973127365112, Accuracy: 0.7281632423400879

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [30]:
# Set the model's file path
from pathlib import Path
file_path = Path("Resources/AlphabetSoup.h5")

# Export your model to a HDF5 file
nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [33]:
# Define the the number of inputs (features) to the model
number_input_features = 100

# Review the number of features
number_input_features

100

In [34]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [35]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = 80

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

80

In [36]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2_A1 = 42

# Review the number of hidden nodes in the second layer
hidden_nodes_layer2_A1

42

In [37]:
# Define the number of hidden nodes for the third hidden layer
hidden_nodes_layer3_A1 = 20

# Review the number of hidden nodes in the second layer
hidden_nodes_layer3_A1

20

In [38]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [39]:

# First hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))
# Output layer
nn.add(Dense(1, activation="sigmoid"))
# Check the structure of the model
# YOUR CODE HERE

In [40]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [41]:
# Fit the model using 50 epochs and the training data
model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 4s 4ms/step - loss: 0.5777 - accuracy: 0.7232
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7405
Epoch 3/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7407
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7395
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5346 - accuracy: 0.7410
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7397
Epoch 7/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5339 - accuracy: 0.7419
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7406
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7409
Epoch 10/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5326 - accuracy: 0.7409
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5328 - accuracy: 0.7402
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5321 - accuracy: 0.7415
Epoch 13/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5321 - accuracy: 0.7410
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5321 - accuracy: 0.7416
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5319 - accuracy: 0.7417
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5312 - accuracy: 0.7417
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5316 - accuracy: 0.7413
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5312 - accuracy: 0.7423
Epoch 19/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5315 - accuracy: 0.7415
Epoch 20/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5308 - accuracy: 0.7418
Epoch 21/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5313 - accuracy: 0.7406
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5308 - accuracy: 0.7421
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5308 - accuracy: 0.7416
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5310 - accuracy: 0.7421
Epoch 25/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5304 - accuracy: 0.7423
Epoch 26/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5308 - accuracy: 0.7425
Epoch 27/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5303 - accuracy: 0.7411
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5308 - accuracy: 0.7417
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5303 - accuracy: 0.7427
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5303 - accuracy: 0.7415
Epoch 31/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5307 - accuracy: 0.7419
Epoch 32/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5303 - accuracy: 0.7432
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5302 - accuracy: 0.7415
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5299 - accuracy: 0.7408
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5297 - accuracy: 0.7420
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5306 - accuracy: 0.7420
Epoch 37/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5298 - accuracy: 0.7429
Epoch 38/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5300 - accuracy: 0.7413
Epoch 39/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5295 - accuracy: 0.7428
Epoch 40/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5300 - accuracy: 0.7419
Epoch 41/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5297 - accuracy: 0.7428
Epoch 42/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5292 - accuracy: 0.7410
Epoch 43/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5297 - accuracy: 0.7429
Epoch 44/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5294 - accuracy: 0.7419
Epoch 45/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5293 - accuracy: 0.7425
Epoch 46/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5296 - accuracy: 0.7410
Epoch 47/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5294 - accuracy: 0.7416
Epoch 48/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5293 - accuracy: 0.7413
Epoch 49/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5289 - accuracy: 0.7422
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5287 - accuracy: 0.7436

In [42]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5585 - accuracy: 0.7278 - 1s/epoch - 5ms/step
Loss: 0.5585366487503052, Accuracy: 0.7278134226799011

#### Alternative Model 2

In [43]:
# Define the the number of inputs (features) to the model
number_input_features =90

# Review the number of features
number_input_features

90

In [44]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [45]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = 90

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

90

In [46]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2_A2 = 70

# Review the number of hidden nodes in the second layer
hidden_nodes_layer2_A2

70

In [47]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [48]:
# First hidden layers
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="tanh"))

# Output layer
nn.add(Dense(1, activation="sigmoid"))

# Check the structure of the model
# YOUR CODE HERE

In [50]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [51]:
# Fit the model
model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 5s 4ms/step - loss: 0.5573 - accuracy: 0.7307
Epoch 2/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5353 - accuracy: 0.7414
Epoch 3/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5336 - accuracy: 0.7408
Epoch 4/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5322 - accuracy: 0.7395
Epoch 5/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5321 - accuracy: 0.7411
Epoch 6/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5316 - accuracy: 0.7408
Epoch 7/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5312 - accuracy: 0.7424
Epoch 8/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5309 - accuracy: 0.7416
Epoch 9/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5318 - accuracy: 0.7411
Epoch 10/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5307 - accuracy: 0.7423
Epoch 11/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5300 - accuracy: 0.7430
Epoch 12/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5300 - accuracy: 0.7421
Epoch 13/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5297 - accuracy: 0.7417
Epoch 14/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5303 - accuracy: 0.7428
Epoch 15/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5303 - accuracy: 0.7421
Epoch 16/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5298 - accuracy: 0.7428
Epoch 17/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5298 - accuracy: 0.7420
Epoch 18/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5299 - accuracy: 0.7413
Epoch 19/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5305 - accuracy: 0.7419
Epoch 20/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5301 - accuracy: 0.7415
Epoch 21/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5294 - accuracy: 0.7410
Epoch 22/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5297 - accuracy: 0.7421
Epoch 23/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5293 - accuracy: 0.7429
Epoch 24/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5291 - accuracy: 0.7414
Epoch 25/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5303 - accuracy: 0.7414
Epoch 26/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5294 - accuracy: 0.7413
Epoch 27/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5293 - accuracy: 0.7430
Epoch 28/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5296 - accuracy: 0.7425
Epoch 29/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5294 - accuracy: 0.7416
Epoch 30/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5294 - accuracy: 0.7423
Epoch 31/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5286 - accuracy: 0.7431
Epoch 32/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5291 - accuracy: 0.7419
Epoch 33/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5298 - accuracy: 0.7412
Epoch 34/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5292 - accuracy: 0.7414
Epoch 35/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5300 - accuracy: 0.7408
Epoch 36/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5298 - accuracy: 0.7422
Epoch 37/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5289 - accuracy: 0.7430
Epoch 38/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5292 - accuracy: 0.7416
Epoch 39/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5291 - accuracy: 0.7440
Epoch 40/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5296 - accuracy: 0.7416
Epoch 41/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5291 - accuracy: 0.7421
Epoch 42/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5284 - accuracy: 0.7427
Epoch 43/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5289 - accuracy: 0.7418
Epoch 44/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5288 - accuracy: 0.7415
Epoch 45/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5291 - accuracy: 0.7414
Epoch 46/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5290 - accuracy: 0.7417
Epoch 47/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5288 - accuracy: 0.7427
Epoch 48/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5292 - accuracy: 0.7411
Epoch 49/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5282 - accuracy: 0.7426
Epoch 50/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5286 - accuracy: 0.7435

In [52]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)


# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5604 - accuracy: 0.7284 - 531ms/epoch - 2ms/step
Loss: 0.5604103207588196, Accuracy: 0.728396475315094

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [ ]:
#print("Original Model Results")

268/268 - 1s - loss: 0.5578 - accuracy: 0.7282 - 521ms/epoch - 2ms/step
Loss: 0.5577973127365112, Accuracy: 0.7281632423400879

In [ ]:
#print("Alternative Model 1 Results")

268/268 - 1s - loss: 0.5585 - accuracy: 0.7278 - 1s/epoch - 5ms/step
Loss: 0.5585366487503052, Accuracy: 0.7278134226799011

In [ ]:
#print("Alternative Model 2 Results")

#268/268 - 1s - loss: 0.5604 - accuracy: 0.7284 - 531ms/epoch - 2ms/step
Loss: 0.5604103207588196, Accuracy: 0.728396475315094

### Step 3: Save each of your alternative models as an HDF5 file.

In [54]:
# Set the model's file path
from pathlib import Path
file_path = Path("Resources/AlphabetSoup_A1.h5")

# Export your model to a HDF5 file
nn.save(file_path)

In [55]:
# Set the model's file path
from pathlib import Path
file_path = Path("Resources/AlphabetSoup_A2.h5")

# Export your model to a HDF5 file
nn.save(file_path)